apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: laravel-aws-pubsub
  annotations:
    github.com/project-slug: yourparkingspace/laravel-aws-pubsub
spec:
  type: service
  lifecycle: production
  owner: parkmaven
